import { useEffect, useState } from 'react';
import Modal from '../../components/Modal';
import { API_BASE_URL, apiFetch } from '../../config';

const emptyForm = { title: '', difficulty: 'Easy', category: '', description: '', starterCode: '', driverTemplate: '', testCases: [{ input: '', expectedOutput: '' }] };

export default function AdminProblems() {
  const [problems, setProblems] = useState([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [open, setOpen] = useState(false); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const response = await apiFetch(`${API_BASE_URL}/api/problems`); if (!response.ok) throw new Error(); setProblems(await response.json()); setError(null); } catch { setError('Could not load problems.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const updateCase = (index, field, value) => setForm((current) => ({ ...current, testCases: current.testCases.map((testCase, i) => i === index ? { ...testCase, [field]: value } : testCase) }));
  const openEdit = (problem) => { setEditingId(problem._id); setForm({ ...problem, testCases: problem.testCases?.length ? problem.testCases.map(({ input, expectedOutput }) => ({ input, expectedOutput })) : [{ input: '', expectedOutput: '' }] }); setOpen(true); setError(null); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const response = await apiFetch(`${API_BASE_URL}/api/admin/problems${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || 'Could not save problem.'); } await load(); setOpen(false); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm('Delete this problem?')) return; try { const response = await apiFetch(`${API_BASE_URL}/api/admin/problems/${id}`, { method: 'DELETE' }); if (!response.ok) throw new Error(); await load(); } catch { setError('Could not delete problem.'); } };
  return <main className="page admin-page"><section className="page-intro"><div><p className="eyebrow">ADMINISTRATION</p><h1>Problems</h1><p className="lede">Create and maintain the problem library.</p></div><button className="button primary" type="button" onClick={() => { setEditingId(null); setForm(emptyForm); setOpen(true); setError(null); }}>Add Problem</button></section>{error && <p className="error admin-error">{error}</p>}{loading ? <p>Loading problems...</p> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Difficulty</th><th>Category</th><th>Actions</th></tr></thead><tbody>{problems.map((problem) => <tr key={problem._id}><td>{problem.title}</td><td><span className={`difficulty ${problem.difficulty.toLowerCase()}`}>{problem.difficulty}</span></td><td>{problem.category}</td><td><button className="table-action" type="button" onClick={() => openEdit(problem)}>Edit</button><button className="table-action danger" type="button" onClick={() => remove(problem._id)}>Delete</button></td></tr>)}</tbody></table></div>}
    <Modal isOpen={open} onClose={() => setOpen(false)}><form className="admin-form" onSubmit={submit}><h2>{editingId ? 'Edit problem' : 'Add problem'}</h2>{['title', 'category'].map((field) => <label key={field}>{field === 'title' ? 'Title' : 'Category'}<input required value={form[field] || ''} onChange={(e) => update(field, e.target.value)} /></label>)}<label>Difficulty<select value={form.difficulty} onChange={(e) => update('difficulty', e.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option></select></label><label>Description<textarea required value={form.description || ''} onChange={(e) => update('description', e.target.value)} /></label>{['starterCode', 'driverTemplate'].map((field) => <label key={field}>{field}<textarea required className="code-field" value={form[field] || ''} onChange={(e) => update(field, e.target.value)} /></label>)}<fieldset><legend>Test cases</legend>{form.testCases.map((testCase, index) => <div className="test-case" key={index}><textarea required className="code-field" aria-label={`Test case ${index + 1} input`} placeholder="Input" value={testCase.input} onChange={(e) => updateCase(index, 'input', e.target.value)} /><textarea required className="code-field" aria-label={`Test case ${index + 1} expected output`} placeholder="Expected output" value={testCase.expectedOutput} onChange={(e) => updateCase(index, 'expectedOutput', e.target.value)} /><button className="table-action danger" type="button" disabled={form.testCases.length === 1} onClick={() => update('testCases', form.testCases.filter((_, i) => i !== index))}>Remove</button></div>)}<button className="button secondary" type="button" onClick={() => update('testCases', [...form.testCases, { input: '', expectedOutput: '' }])}>Add test case</button></fieldset><button className="button primary" type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save problem'}</button></form></Modal>
  </main>;
}
